# Generated by Django 5.1.6 on 2025-02-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('photo', models.URLField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('thumbnail', models.URLField(blank=True)),
                ('num_lectures', models.IntegerField(default=0)),
                ('subscribers', models.IntegerField(default=0)),
                ('price', models.CharField(default='Free', max_length=50)),
                ('currency', models.CharField(default='Unknown', max_length=50)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.instructor')),
            ],
        ),
    ]
